apiVersion: v1
kind: Pod
metadata:
  name: test1
  labels: 
    app: front
    env: prod
spec:
  containers:
  - image: nginx:1.26.1
    name: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels: 
    app: backend
    env: prod
spec:
  containers:
  - image: nginx:1.26.1
    name: nginx