apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: default
  labels:
    app: cm-app
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm-vars
  namespace: default
  labels:
    app: cm-app
data:
  db_host: dev.host.local
  db_user: dev.user
  script: |
    echo DB HOST es $DB_HOST y USER es $DB_USER > /usr/share/nginx/html/test.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "image test"
  name: configmap-test
  labels:
    app: cm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-app
  template:
    metadata:
      labels:
        app: cm-app
    spec:
      containers:
      - name: configmap-test
        image: nginx:alpine
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: nginx-cm-vars           
                key: db_host 
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: nginx-cm-vars           
                key: db_user 
        resources:
          requests:
            memory: "100Mi"
            cpu: 500m
          limits:
            memory: "200Mi"
            cpu: 700m
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: nginx-vol
          mountPath: /etc/nginx/conf.d/
        - name: script-vol
          mountPath: /opt
      volumes:
      - name: nginx-vol
        configMap:
          name: nginx-cm
          items:
            - key: nginx.conf
              path: default.conf
      - name: script-vol
        configMap:
          name: nginx-cm-vars
          items:
            - key: script
              path: script.sh

