apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
  namespace: default
  labels:
    app: cm-app
data:
  test: hola
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "image test"
  name: configmap-test
  labels:
    app: cm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-app
  template:
    metadata:
      labels:
        app: cm-app
    spec:
      containers:
      - name: configmap-test
        image: nginx:alpine
        resources:
          requests:
            memory: "100Mi"
            cpu: 500m
          limits:
            memory: "200Mi"
            cpu: 700m
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-vol
          mountPath: /etc/nginx/conf.d/
          readOnly: true
      volumes:
      - name: nginx-vol
        configMap:
          name: nginx-cm

