apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
spec:
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: dev
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
