apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-test
  labels:
    app: rs-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs-test
  template:
    metadata:
      labels:
        app: rs-test
    spec:
      containers:
      - image: python:3.6-alpine
        name: python-c1
        command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8081']
      - image: python:3.6-alpine
        name: python-c2
        command: ['sh', '-c', 'echo cont12> index.html && python -m http.server 8082']
