apiVersion: v1
kind: Secret
metadata:
  name: secret-5
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: password
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  containers:
    - name: dotfile-test-container
      image: rnginx:alpíne
      resources:
        limits:
          cpu: 500m
          memory: 200Mi
        requests:
          cpu: 500m
          memory: 100Mi
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/opt"
  volumes:
    - name: secret-volume
      secret:
        secretName: dosecret-5
        items:
        - username:
          path: 